defaults:
  - dataset: cath
  - model: egnn
  - diffusion: discrete_default
  - comet: basic
  - mask_prior: default

hydra:
  run:
    dir: ./outputs/evaluation_${now:%Y-%m-%d}_${now:%H-%M-%S}
  output_subdir: configs

experiment:
  name: MapDiff_Evaluation

evaluation:
  checkpoint_path: ./mapdiff_weight.pt
  batch_size: 4
  num_workers: 16
  ensemble_num: 50    # Number of ensemble predictions
  ddim_steps: 10      # DDIM sampling steps
  evaluate_val: true
  evaluate_test: true
  # Optimization settings
  fast_eval: false    # Set to true for faster evaluation with reduced ensemble
  fast_ensemble_num: 10  # Ensemble size when fast_eval is true
  use_amp: false      # Use automatic mixed precision (requires GPU) - may affect numerical results
  use_compile: true   # Use torch.compile (requires PyTorch 2.0+)
  # Multi-GPU settings
  use_multi_gpu: true   # Set to true to use multiple GPUs (task-based parallelism)
  max_gpus: 8          # Maximum number of GPUs to use
  num_cpu_workers: 32  # Number of CPU workers for data loading (up to 128)
  batch_size: 4        # Number of proteins to process per GPU batch (improves GPU utilization)
  
logging:
  save_tables: true      # Save PrettyTable output
  save_json: true        # Save results as JSON
  save_csv: true         # Save results as CSV
  use_comet: true        # Use Comet ML logging (requires API key)
  verbose: true          # Print detailed progress

prior_model:
  path: none  # Not needed for evaluation since it's loaded from checkpoint